/* Visualizacao´s Form generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05 */  
import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import { Alert, Button, FormGroup, ControlLabel, FormControl, HelpBlock } from "react-bootstrap";

import HttpRequest from "../core/HttpRequest";
import JSInputField from "../core/JSInputField";
import JSCombobox from "../core/JSCombobox";
import Message from "../core/Message";

import ModalFilme from "../filme/ModalFilme";
import ModalAssinante from "../assinante/ModalAssinante";

import { isEmpty, isNotEmpty } from "../core/JSUtils";

const emptyVisualizacao = {
	id: '',
	dataHora: '',    	
	percentualAssistido: '',    	
};

export default class FormVisualizacao extends React.Component {
    constructor() {
        super();
        this.service = new HttpRequest("/rs/crud/visualizacaos");
        
        this.state = {
            visualizacao: emptyVisualizacao,
		
            message: new Message(),
            showMessage: false,

            validationFields: {
            }
        }
    }
    componentDidMount = () => {
    
    }
    getValidationState = (fieldName) => {
        if (this.state.validationFields[fieldName]) {
            if (!(this.state.validationFields[fieldName].isValid())) {
                return "error";
            }
        }
        return null;
    }
    
	getValidationMessage = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.message;
        }
        return false;
    }
    
    validateField = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.isValid && fieldValidator.isValid();
        }
        return "";
    }

    submitFormHandle = (clickEvent) => {
        console.log("Salvando o objeto: " + this.state.visualizacao);
        this.service.save(
            this.state.visualizacao,
            data => {
                this.visualizacao = data;
				this.setState({ message: new Message("success", "Success saving Visualizacao"), showMessage: true })
                this.setState({ visualizacao: emptyVisualizacao });

            },
            error => {
                console.error("error saving visualizacao ", error);
				this.setState({ message: new Message("danger", "Error saving Visualizacao"), showMessage: true })
            }
        );
    }

    changeFormDateHandle = (name, value) => {
    	const visualizacao = { ...this.state.visualizacao };
        visualizacao[name] = value;
        this.setState({ visualizacao });
    }

    render = () => {
        return (
            <div className="panel">
                <div className="panel-heading">
                    <h3 className="panel-title">Cadastro de Visualização</h3>
                </div>
                <div className="panel-body">
                    <div className="panel">
                        <div className="panel-body">
                            {this.state.showMessage ?
                                <Alert bsStyle={this.state.message.type} onDismiss={() => { this.setState({ showMessage: false }) }}>
                                    {this.state.message.text}
                                </Alert>
                                
                                : null
                            }                        
                            <form>
                                <FormGroup controlId="dataHora" validationState={this.getValidationState("dataHora")} >
                                    <ControlLabel>Data hora</ControlLabel>
                                    <JSInputField name="dataHora" plugin="datetime" type="text" value={this.state.visualizacao.dataHora}  onChange={(event) => this.changeFormDateHandle("dataHora", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("dataHora") ? "hide" : "block"} >{this.getValidationMessage("dataHora")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="percentualAssistido" validationState={this.getValidationState("percentualAssistido")} >
                                    <ControlLabel>Percentual assistido</ControlLabel>
                                    <JSInputField name="percentualAssistido" type="text" value={this.state.visualizacao.percentualAssistido}  onChange={(event) => this.changeFormDateHandle("percentualAssistido", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("percentualAssistido") ? "hide" : "block"} >{this.getValidationMessage("percentualAssistido")}</HelpBlock>
                                </FormGroup>
                                
		                        <FormGroup controlId="titulo" validationState={this.getValidationState("filme")} >
		                            <ControlLabel>Filme</ControlLabel>
		                            <FormControl.Feedback />
									<ModalFilme value={this.state.visualizacao.filme} displayValue="tituloOriginal" idValue="id" onChange={(event) => this.changeFormDateHandle("filme", event.target.value)}  />
		                            <HelpBlock className={this.validateField("filme") ? "hide" : "block"} >{this.getValidationMessage("filme")}</HelpBlock>
		                        </FormGroup>
		                              					
		                        <FormGroup controlId="titulo" validationState={this.getValidationState("assinante")} >
		                            <ControlLabel>Assinante</ControlLabel>
		                            <FormControl.Feedback />
									<ModalAssinante value={this.state.visualizacao.assinante} displayValue="nome" idValue="id" onChange={(event) => this.changeFormDateHandle("assinante", event.target.value)}  />
		                            <HelpBlock className={this.validateField("assinante") ? "hide" : "block"} >{this.getValidationMessage("assinante")}</HelpBlock>
		                        </FormGroup>
		                              					
                            </form>
                        </div>
                    </div >
                    <div >
                        <div className="clearfix form-actions">
                            <button onClick={this.submitFormHandle} className="btn btn-primary btn-lg " >
                                <i className="fa fa-check " />
                                &nbsp; Salvar
                            </button>
                            &nbsp;
                            <button onClick={this.handleClick} className="btn btn-primary btn-lg ">
                                <i className="fa fa-check " />
                                &nbsp; Salvar e continuar
                            </button>
                            &nbsp;
                            
                            <NavLink to="/visualizacaos/list" className="btn-lg btn btn-light">
								<i className=" fa fa-undo " />
                                &nbsp; Voltar para a listagem
                             </NavLink>
                        </div >
                    </div >
                </div >
            </div >
        )
    }
}

