package br.com.netflics.core.security;

import br.com.netflics.model.User;
/**
*  generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05
**/

public interface UserContext {

	User getCurrentUser();

	String getCurrentUserName();
	
	void setCurrentUser(User user);
}
