package br.com.netflics.core.security;

import java.util.ArrayList;

import java.util.Collection;
import java.util.List;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

import br.com.netflics.model.User;
import br.com.netflics.model.Role;

/**
*  generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05
**/

public final class UserAuthorityUtils {

	public static final List<GrantedAuthority> AUTHORITIES = new ArrayList<GrantedAuthority>();

	public static Collection<? extends GrantedAuthority> createAuthorities(User user) {
		List<Role> roles = user.getRoles();

		if (roles != null) {
			AUTHORITIES.clear();
			for (Role role : roles) {
				String authority = role.getAuthority();
				SimpleGrantedAuthority simpleGrantedAuthority = new SimpleGrantedAuthority(authority);
				AUTHORITIES.add(simpleGrantedAuthority);
			}
		}
		return AUTHORITIES;
	}

	private UserAuthorityUtils() {

	}
}