package br.com.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
public class FilterVisualizacao implements Serializable {
	private static final long serialVersionUID = 1L;
	private LocalDateTime dataHora;
	private String percentualAssistido;  			

	private Integer filme;		
	private Integer assinante;		
	
	public  FilterVisualizacao() {
		
	}

	public LocalDateTime getDataHora() {
		return dataHora;
	}

	public void setDataHora(LocalDateTime dataHora) {
		this.dataHora = dataHora;
	}
	public String getPercentualAssistido() {
		return percentualAssistido;
	}

	public void setPercentualAssistido(String percentualAssistido) {
		this.percentualAssistido = percentualAssistido;
	}
		
	public Integer getFilme() {
		return filme;
	}
	
	public void setFilme(Integer filme) {
		this.filme = filme;
	}
	public Integer getAssinante() {
		return assinante;
	}
	
	public void setAssinante(Integer assinante) {
		this.assinante = assinante;
	}
}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06