package br.com.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
public class FilterAtor implements Serializable {
	private static final long serialVersionUID = 1L;
	private String biografia;  			
	private LocalDate dataNascimento;  			
	private String nome;  			
	private String foto;  			

	
	public  FilterAtor() {
		
	}

	public String getBiografia() {
		return biografia;
	}

	public void setBiografia(String biografia) {
		this.biografia = biografia;
	}
	public LocalDate getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(LocalDate dataNascimento) {
		this.dataNascimento = dataNascimento;
	}
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getFoto() {
		return foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}
		
}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06