package br.com.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
public class FilterGenero implements Serializable {
	private static final long serialVersionUID = 1L;
	private String nome;  			
	private String descricao;  			

	
	public  FilterGenero() {
		
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
		
}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06