/* Linguagem´s Form generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05 */  
import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import { Alert, Button, FormGroup, ControlLabel, FormControl, HelpBlock } from "react-bootstrap";

import HttpRequest from "../core/HttpRequest";
import JSInputField from "../core/JSInputField";
import JSCombobox from "../core/JSCombobox";
import Message from "../core/Message";


import { isEmpty, isNotEmpty } from "../core/JSUtils";

const emptyLinguagem = {
	id: '',
	nome: '',    	
};

export default class FormLinguagem extends React.Component {
    constructor() {
        super();
        this.service = new HttpRequest("/rs/crud/linguagems");
        
        this.state = {
            linguagem: emptyLinguagem,
		
            message: new Message(),
            showMessage: false,

            validationFields: {
                nome: {
                    isValid: () => {
                        return isNotEmpty(this.state.linguagem.nome);
                    },
                    message: "Campo Obrigatório!",
                },
            }
        }
    }
    componentDidMount = () => {
    
    }
    getValidationState = (fieldName) => {
        if (this.state.validationFields[fieldName]) {
            if (!(this.state.validationFields[fieldName].isValid())) {
                return "error";
            }
        }
        return null;
    }
    
	getValidationMessage = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.message;
        }
        return false;
    }
    
    validateField = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.isValid && fieldValidator.isValid();
        }
        return "";
    }

    submitFormHandle = (clickEvent) => {
        console.log("Salvando o objeto: " + this.state.linguagem);
        this.service.save(
            this.state.linguagem,
            data => {
                this.linguagem = data;
				this.setState({ message: new Message("success", "Success saving Linguagem"), showMessage: true })
                this.setState({ linguagem: emptyLinguagem });

            },
            error => {
                console.error("error saving linguagem ", error);
				this.setState({ message: new Message("danger", "Error saving Linguagem"), showMessage: true })
            }
        );
    }

    changeFormDateHandle = (name, value) => {
    	const linguagem = { ...this.state.linguagem };
        linguagem[name] = value;
        this.setState({ linguagem });
    }

    render = () => {
        return (
            <div className="panel">
                <div className="panel-heading">
                    <h3 className="panel-title">Cadastro de Linguagem</h3>
                </div>
                <div className="panel-body">
                    <div className="panel">
                        <div className="panel-body">
                            {this.state.showMessage ?
                                <Alert bsStyle={this.state.message.type} onDismiss={() => { this.setState({ showMessage: false }) }}>
                                    {this.state.message.text}
                                </Alert>
                                
                                : null
                            }                        
                            <form>
                                <FormGroup controlId="nome" validationState={this.getValidationState("nome")} >
                                    <ControlLabel>Nome</ControlLabel>
                                    <JSInputField name="nome" type="text" value={this.state.linguagem.nome}  onChange={(event) => this.changeFormDateHandle("nome", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("nome") ? "hide" : "block"} >{this.getValidationMessage("nome")}</HelpBlock>
                                </FormGroup>
                                
                            </form>
                        </div>
                    </div >
                    <div >
                        <div className="clearfix form-actions">
                            <button onClick={this.submitFormHandle} className="btn btn-primary btn-lg " >
                                <i className="fa fa-check " />
                                &nbsp; Salvar
                            </button>
                            &nbsp;
                            <button onClick={this.handleClick} className="btn btn-primary btn-lg ">
                                <i className="fa fa-check " />
                                &nbsp; Salvar e continuar
                            </button>
                            &nbsp;
                            
                            <NavLink to="/linguagems/list" className="btn-lg btn btn-light">
								<i className=" fa fa-undo " />
                                &nbsp; Voltar para a listagem
                             </NavLink>
                        </div >
                    </div >
                </div >
            </div >
        )
    }
}

