/* User´s Form generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05 */  
import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import { Alert, Button, FormGroup, ControlLabel, FormControl, HelpBlock } from "react-bootstrap";

import HttpRequest from "../core/HttpRequest";
import JSInputField from "../core/JSInputField";
import JSCombobox from "../core/JSCombobox";
import Message from "../core/Message";


import { isEmpty, isNotEmpty } from "../core/JSUtils";

const emptyUser = {
	id: '',
	name: '',    	
	username: '',    	
	email: '',    	
	password: '',    	
	enable: '',    	
	image: '',    	
};

export default class FormUser extends React.Component {
    constructor() {
        super();
        this.service = new HttpRequest("/rs/crud/users");
        
        this.state = {
            user: emptyUser,
		
            message: new Message(),
            showMessage: false,

            validationFields: {
                name: {
                    isValid: () => {
                        return isNotEmpty(this.state.user.name);
                    },
                    message: "Campo Obrigatório!",
                },
                username: {
                    isValid: () => {
                        return isNotEmpty(this.state.user.username);
                    },
                    message: "Campo Obrigatório!",
                },
                email: {
                    isValid: () => {
                        return isNotEmpty(this.state.user.email);
                    },
                    message: "Campo Obrigatório!",
                },
                password: {
                    isValid: () => {
                        return isNotEmpty(this.state.user.password);
                    },
                    message: "Campo Obrigatório!",
                },
            }
        }
    }
    componentDidMount = () => {
    
    }
    getValidationState = (fieldName) => {
        if (this.state.validationFields[fieldName]) {
            if (!(this.state.validationFields[fieldName].isValid())) {
                return "error";
            }
        }
        return null;
    }
    
	getValidationMessage = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.message;
        }
        return false;
    }
    
    validateField = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.isValid && fieldValidator.isValid();
        }
        return "";
    }

    submitFormHandle = (clickEvent) => {
        console.log("Salvando o objeto: " + this.state.user);
        this.service.save(
            this.state.user,
            data => {
                this.user = data;
				this.setState({ message: new Message("success", "Success saving User"), showMessage: true })
                this.setState({ user: emptyUser });

            },
            error => {
                console.error("error saving user ", error);
				this.setState({ message: new Message("danger", "Error saving User"), showMessage: true })
            }
        );
    }

    changeFormDateHandle = (name, value) => {
    	const user = { ...this.state.user };
        user[name] = value;
        this.setState({ user });
    }

    render = () => {
        return (
            <div className="panel">
                <div className="panel-heading">
                    <h3 className="panel-title">Cadastro de Usuário</h3>
                </div>
                <div className="panel-body">
                    <div className="panel">
                        <div className="panel-body">
                            {this.state.showMessage ?
                                <Alert bsStyle={this.state.message.type} onDismiss={() => { this.setState({ showMessage: false }) }}>
                                    {this.state.message.text}
                                </Alert>
                                
                                : null
                            }                        
                            <form>
                                <FormGroup controlId="name" validationState={this.getValidationState("name")} >
                                    <ControlLabel>Nome</ControlLabel>
                                    <JSInputField name="name" type="text" value={this.state.user.name}  onChange={(event) => this.changeFormDateHandle("name", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("name") ? "hide" : "block"} >{this.getValidationMessage("name")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="username" validationState={this.getValidationState("username")} >
                                    <ControlLabel>Username</ControlLabel>
                                    <JSInputField name="username" type="text" value={this.state.user.username}  onChange={(event) => this.changeFormDateHandle("username", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("username") ? "hide" : "block"} >{this.getValidationMessage("username")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="email" validationState={this.getValidationState("email")} >
                                    <ControlLabel>E-mail</ControlLabel>
                                    <JSInputField name="email" type="text" value={this.state.user.email}  onChange={(event) => this.changeFormDateHandle("email", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("email") ? "hide" : "block"} >{this.getValidationMessage("email")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="password" validationState={this.getValidationState("password")} >
                                    <ControlLabel>Senha</ControlLabel>
                                    <JSInputField name="password" type="text" value={this.state.user.password}  onChange={(event) => this.changeFormDateHandle("password", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("password") ? "hide" : "block"} >{this.getValidationMessage("password")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="enable" validationState={this.getValidationState("enable")} >
                                    <ControlLabel>Ativo?</ControlLabel>
                                    <JSInputField name="enable" type="text" value={this.state.user.enable}  onChange={(event) => this.changeFormDateHandle("enable", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("enable") ? "hide" : "block"} >{this.getValidationMessage("enable")}</HelpBlock>
                                </FormGroup>
                                
                                <FormGroup controlId="image" validationState={this.getValidationState("image")} >
                                    <ControlLabel>Foto</ControlLabel>
                                    <JSInputField name="image" type="text" value={this.state.user.image}  onChange={(event) => this.changeFormDateHandle("image", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("image") ? "hide" : "block"} >{this.getValidationMessage("image")}</HelpBlock>
                                </FormGroup>
                                
                            </form>
                        </div>
                    </div >
                    <div >
                        <div className="clearfix form-actions">
                            <button onClick={this.submitFormHandle} className="btn btn-primary btn-lg " >
                                <i className="fa fa-check " />
                                &nbsp; Salvar
                            </button>
                            &nbsp;
                            <button onClick={this.handleClick} className="btn btn-primary btn-lg ">
                                <i className="fa fa-check " />
                                &nbsp; Salvar e continuar
                            </button>
                            &nbsp;
                            
                            <NavLink to="/users/list" className="btn-lg btn btn-light">
								<i className=" fa fa-undo " />
                                &nbsp; Voltar para a listagem
                             </NavLink>
                        </div >
                    </div >
                </div >
            </div >
        )
    }
}

