/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05 */
package br.com.netflics.persistence;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import br.com.netflics.model.Linguagem;
	
public interface LinguagemRepository extends JpaRepository<Linguagem, Integer> ,JpaSpecificationExecutor<Linguagem>{

}

//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05