package br.com.netflics.core.persistence.pagination;

import java.util.List;
/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:04 */
public class Pagination<T> {

	private final Long totalRecords;
	private final List<T> results;

	public Pagination(Long totalRecords, List<T> results) {
		this.totalRecords = totalRecords;
		this.results = results;
	}

	public List<T> getResults() {
		return results;
	}

	public Long getTotalRecords() {
		return totalRecords;
	}
}