/* Avaliacao´s Form generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05 */  
import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import { Alert, Button, FormGroup, ControlLabel, FormControl, HelpBlock } from "react-bootstrap";

import HttpRequest from "../core/HttpRequest";
import JSInputField from "../core/JSInputField";
import JSCombobox from "../core/JSCombobox";
import Message from "../core/Message";


import { isEmpty, isNotEmpty } from "../core/JSUtils";

const emptyAvaliacao = {
	id: '',
	dataHora: '',    	
};

export default class FormAvaliacao extends React.Component {
    constructor() {
        super();
        this.service = new HttpRequest("/rs/crud/avaliacaos");
        
        this.state = {
            avaliacao: emptyAvaliacao,
		
            message: new Message(),
            showMessage: false,

            validationFields: {
            }
        }
    }
    componentDidMount = () => {
    
    }
    getValidationState = (fieldName) => {
        if (this.state.validationFields[fieldName]) {
            if (!(this.state.validationFields[fieldName].isValid())) {
                return "error";
            }
        }
        return null;
    }
    
	getValidationMessage = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.message;
        }
        return false;
    }
    
    validateField = (fieldName) => {
        const fieldValidator = this.state.validationFields[fieldName];
        if (fieldValidator) {
            return fieldValidator.isValid && fieldValidator.isValid();
        }
        return "";
    }

    submitFormHandle = (clickEvent) => {
        console.log("Salvando o objeto: " + this.state.avaliacao);
        this.service.save(
            this.state.avaliacao,
            data => {
                this.avaliacao = data;
				this.setState({ message: new Message("success", "Success saving Avaliacao"), showMessage: true })
                this.setState({ avaliacao: emptyAvaliacao });

            },
            error => {
                console.error("error saving avaliacao ", error);
				this.setState({ message: new Message("danger", "Error saving Avaliacao"), showMessage: true })
            }
        );
    }

    changeFormDateHandle = (name, value) => {
    	const avaliacao = { ...this.state.avaliacao };
        avaliacao[name] = value;
        this.setState({ avaliacao });
    }

    render = () => {
        return (
            <div className="panel">
                <div className="panel-heading">
                    <h3 className="panel-title">Cadastro de Avaliação</h3>
                </div>
                <div className="panel-body">
                    <div className="panel">
                        <div className="panel-body">
                            {this.state.showMessage ?
                                <Alert bsStyle={this.state.message.type} onDismiss={() => { this.setState({ showMessage: false }) }}>
                                    {this.state.message.text}
                                </Alert>
                                
                                : null
                            }                        
                            <form>
                                <FormGroup controlId="dataHora" validationState={this.getValidationState("dataHora")} >
                                    <ControlLabel>Data hora</ControlLabel>
                                    <JSInputField name="dataHora" plugin="datetime" type="text" value={this.state.avaliacao.dataHora}  onChange={(event) => this.changeFormDateHandle("dataHora", event.target.value)} className="form-control" />
                                    <FormControl.Feedback />
                                    <HelpBlock className={this.validateField("dataHora") ? "hide" : "block"} >{this.getValidationMessage("dataHora")}</HelpBlock>
                                </FormGroup>
                                
                            </form>
                        </div>
                    </div >
                    <div >
                        <div className="clearfix form-actions">
                            <button onClick={this.submitFormHandle} className="btn btn-primary btn-lg " >
                                <i className="fa fa-check " />
                                &nbsp; Salvar
                            </button>
                            &nbsp;
                            <button onClick={this.handleClick} className="btn btn-primary btn-lg ">
                                <i className="fa fa-check " />
                                &nbsp; Salvar e continuar
                            </button>
                            &nbsp;
                            
                            <NavLink to="/avaliacaos/list" className="btn-lg btn btn-light">
								<i className=" fa fa-undo " />
                                &nbsp; Voltar para a listagem
                             </NavLink>
                        </div >
                    </div >
                </div >
            </div >
        )
    }
}

