/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05 */
package br.com.netflics.core.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EntityListeners;
import javax.persistence.MappedSuperclass;
import java.time.LocalDateTime;

import br.com.netflics.core.persistence.DataCreateUpdateListener;

@EntityListeners(DataCreateUpdateListener.class)
@MappedSuperclass
public abstract class AbstractEntity implements Serializable {

	private static final long serialVersionUID = -7964355524118760783L;
	@Column(name = "CREATE_DATETIME", insertable = true, updatable = false)
	private LocalDateTime createDatetime;

	@Column(name = "LAST_UPDATE_DATETIME")
	private LocalDateTime lastUpdateDatetime;

	@Column(name = "USER_CREATE", insertable = true, updatable = false)
	private String userCreate;

	@Column(name = "USER_CHANGE")
	private String userChange;

	public LocalDateTime getCreateDatetime() {
		return createDatetime;
	}

	public void setCreateDatetime(LocalDateTime createDatetime) {
		this.createDatetime = createDatetime;
	}

	public LocalDateTime getLastUpdateDatetime() {
		return lastUpdateDatetime;
	}

	public void setLastUpdateDatetime(LocalDateTime lastUpdateDatetime) {
		this.lastUpdateDatetime = lastUpdateDatetime;
	}

	public String getUserCreate() {
		return userCreate;
	}

	public void setUserCreate(String userCreate) {
		this.userCreate = userCreate;
	}

	public String getUserChange() {
		return userChange;
	}

	public void setUserChange(String userChange) {
		this.userChange = userChange;
	}
}