/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Assinante;
import br.com.netflics.model.filter.FilterAssinante;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface AssinanteService {

	
	public Optional<Assinante> get(Integer id, Tenant tenant) ;

	public Pager<Assinante> get(SearchParameters<FilterAssinante> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Assinante save(Assinante entity) ;

	public Assinante update(Assinante entity) ;

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06