/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Avaliacao;
import br.com.netflics.model.filter.FilterAvaliacao;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface AvaliacaoService {

	
	public Optional<Avaliacao> get(Integer id, Tenant tenant) ;

	public Pager<Avaliacao> get(SearchParameters<FilterAvaliacao> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Avaliacao save(Avaliacao entity) ;

	public Avaliacao update(Avaliacao entity) ;

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06