/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Classificacao;
import br.com.netflics.model.filter.FilterClassificacao;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface ClassificacaoService {

	
	public Optional<Classificacao> get(Integer id, Tenant tenant) ;

	public Pager<Classificacao> get(SearchParameters<FilterClassificacao> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Classificacao save(Classificacao entity) ;

	public Classificacao update(Classificacao entity) ;

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06