/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Critico;
import br.com.netflics.model.filter.FilterCritico;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface CriticoService {

	
	public Optional<Critico> get(Integer id, Tenant tenant) ;

	public Pager<Critico> get(SearchParameters<FilterCritico> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Critico save(Critico entity) ;

	public Critico update(Critico entity) ;

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06