/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Filme;
import br.com.netflics.model.filter.FilterFilme;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface FilmeService {

	
	public Optional<Filme> get(Integer id, Tenant tenant) ;

	public Pager<Filme> get(SearchParameters<FilterFilme> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Filme save(Filme entity) ;

	public Filme update(Filme entity) ;

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06