/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.service;

import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import br.com.netflics.core.model.Tenant ;

import br.com.netflics.model.Filme;
import br.com.netflics.persistence.FilmeRepository;
import br.com.netflics.persistence.FilmeSpecificationHelper;
import br.com.netflics.model.filter.FilterFilme;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.rs.exception.ValidationException;
import br.com.netflics.core.persistence.pagination.SearchParameters;
import br.com.netflics.core.utils.DateUtil;
import br.com.netflics.core.utils.Util;

@Service
@Transactional
public class FilmeServiceImp implements FilmeService {

	public static final Logger LOGGER = LoggerFactory.getLogger(FilmeServiceImp.class);
	
	@Autowired
	FilmeRepository filmeRepository;
	
	public Optional<Filme> get(Integer id, Tenant tenant) {
		return filmeRepository.findOne(FilmeSpecificationHelper.fromId(id, tenant));
	}

	public Pager<Filme> get(SearchParameters<FilterFilme> searchParams, Tenant tenant) {
		Pageable pageRequest = searchParams.getPageRequest();

		Page<Filme> page = filmeRepository.findAll(FilmeSpecificationHelper.filter(searchParams, tenant), pageRequest);

		return new Pager<Filme>(page.getContent(), searchParams.getPage(), searchParams.getPageSize(),
		        searchParams.getOrder(), searchParams.getOrderBy(), page.getTotalElements());
	}

	public Boolean delete(Integer id, Tenant tenant) {
		Optional<Filme> optional = this.get(id, tenant);
		if (optional.isPresent()) {
			filmeRepository.delete(optional.get());
		}
		return true;
	}

	public Filme save(Filme entity) {
		return filmeRepository.save(entity);
	}

	public Filme update(Filme entity) {
		return filmeRepository.save(entity);
	}
}

//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06