/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Genero;
import br.com.netflics.model.filter.FilterGenero;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface GeneroService {

	
	public Optional<Genero> get(Integer id, Tenant tenant) ;

	public Pager<Genero> get(SearchParameters<FilterGenero> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Genero save(Genero entity) ;

	public Genero update(Genero entity) ;

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06