/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Group;
import br.com.netflics.model.filter.FilterGroup;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface GroupService {

	
	public Optional<Group> get(Integer id) ;

	public Pager<Group> get(SearchParameters<FilterGroup> searchParams) ;
	
	public Boolean delete(Integer id);

	public Group save(Group entity) ;

	public Group update(Group entity) ;

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06