/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Linguagem;
import br.com.netflics.model.filter.FilterLinguagem;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface LinguagemService {

	
	public Optional<Linguagem> get(Integer id, Tenant tenant) ;

	public Pager<Linguagem> get(SearchParameters<FilterLinguagem> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Linguagem save(Linguagem entity) ;

	public Linguagem update(Linguagem entity) ;

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06