/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Visualizacao;
import br.com.netflics.model.filter.FilterVisualizacao;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface VisualizacaoService {

	
	public Optional<Visualizacao> get(Integer id, Tenant tenant) ;

	public Pager<Visualizacao> get(SearchParameters<FilterVisualizacao> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Visualizacao save(Visualizacao entity) ;

	public Visualizacao update(Visualizacao entity) ;

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06