package br.com.netflics.json;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import java.time.LocalDate;
import java.time.LocalDateTime;


/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
public class JsonAtor implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String biografia;
	private LocalDate dataNascimento;  			
	private String nome;
	private String foto;
	private ArrayList<JsonFilme> filmes = new ArrayList<JsonFilme>();	
	
	public  JsonAtor() {
		
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getBiografia() {
		return biografia;
	}

	public void setBiografia(String biografia) {
		this.biografia = biografia;
	}
	public LocalDate getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(LocalDate dataNascimento) {
		this.dataNascimento = dataNascimento;
	}				
								
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getFoto() {
		return foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}
	
	public ArrayList<JsonFilme> getFilmes() {
		return filmes;
	}
	
	public void setFilmes(ArrayList<JsonFilme> filme) {
		this.filmes = filme;
	}


}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06