package br.com.netflics.json;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import java.time.LocalDate;
import java.time.LocalDateTime;


/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
public class JsonAssinante implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String telefone;
	private Double desconto;
	private LocalDate dataVencimento;  			
	private String cpf;
	private String nome;
	private Double valorMensalidade;
	private String observacao;
	private Boolean ativo;
	private String foto;
	private String celular;
	private String rg;
	private LocalDateTime dataHoraAssinatura;
	private LocalDate dataNascimento;  			
	private ArrayList<JsonFilme> minhaLista = new ArrayList<JsonFilme>();		
	
	public  JsonAssinante() {
		
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}
	public Double getDesconto() {
		return desconto;
	}

	public void setDesconto(Double desconto) {
		this.desconto = desconto;
	}
	public LocalDate getDataVencimento() {
		return dataVencimento;
	}

	public void setDataVencimento(LocalDate dataVencimento) {
		this.dataVencimento = dataVencimento;
	}				
								
	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	public Double getValorMensalidade() {
		return valorMensalidade;
	}

	public void setValorMensalidade(Double valorMensalidade) {
		this.valorMensalidade = valorMensalidade;
	}
	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}
	public Boolean getAtivo() {
		return ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}
	public String getFoto() {
		return foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}
	public String getCelular() {
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}
	public String getRg() {
		return rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}
	public LocalDateTime getDataHoraAssinatura() {
		return dataHoraAssinatura;
	}

	public void setDataHoraAssinatura(LocalDateTime dataHoraAssinatura) {
		this.dataHoraAssinatura = dataHoraAssinatura;
	}				
	public LocalDate getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(LocalDate dataNascimento) {
		this.dataNascimento = dataNascimento;
	}				
								
	
	public ArrayList<JsonFilme> getMinhaLista() {
		return minhaLista;
	}
	
	public void setMinhaLista(ArrayList<JsonFilme> filme) {
		this.minhaLista = filme;
	}


}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06