package br.com.netflics.json;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import java.time.LocalDate;
import java.time.LocalDateTime;


/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
public class JsonVisualizacao implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private LocalDateTime dataHora;
	private String percentualAssistido;
	private JsonFilme filme;		
	private JsonAssinante assinante;		
	
	public  JsonVisualizacao() {
		
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public LocalDateTime getDataHora() {
		return dataHora;
	}

	public void setDataHora(LocalDateTime dataHora) {
		this.dataHora = dataHora;
	}				
	public String getPercentualAssistido() {
		return percentualAssistido;
	}

	public void setPercentualAssistido(String percentualAssistido) {
		this.percentualAssistido = percentualAssistido;
	}
	
	public JsonFilme getFilme() {
		return filme;
	}
	
	public void setFilme(JsonFilme filme) {
		this.filme = filme;
	}
	public JsonAssinante getAssinante() {
		return assinante;
	}
	
	public void setAssinante(JsonAssinante assinante) {
		this.assinante = assinante;
	}

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06