package br.com.netflics.json;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import java.time.LocalDate;
import java.time.LocalDateTime;


/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05 */
public class JsonLinguagem implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nome;
	
	public  JsonLinguagem() {
		
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	

}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:05