/* generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06 */
package br.com.netflics.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.UniqueConstraint;		

import java.time.LocalDate;
import java.time.LocalDateTime;
	
import java.util.ArrayList;
import java.util.List;

import br.com.netflics.core.model.AbstractMultitenantEntity;

@Entity
@Table(name = "ASSINANTE", uniqueConstraints = {
		@UniqueConstraint(name = "ASSINANTE_CPF", columnNames = { "CPF",  "ID_TENANT"}), 
		@UniqueConstraint(name = "ASSINANTE_NOME", columnNames = { "NOME",  "ID_TENANT"}), 
})
public class Assinante extends AbstractMultitenantEntity{
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)	
	private Integer id;
	
	@Column(name = "TELEFONE" )
	private String telefone;		
	
	@Column(name = "DESCONTO")
	private Double desconto;  	
			
	@Column(name = "DATA_VENCIMENTO")
	private LocalDate dataVencimento;  
				
	@Column(name = "CPF" )
	private String cpf;		
	
	@Column(name = "NOME" )
	private String nome;		
	
	@Column(name = "VALOR_MENSALIDADE")
	private Double valorMensalidade;  	
			
	@Column(name = "OBSERVACAO" , columnDefinition="varchar" ) 
	private String observacao;		
	
	@Column(name = "ATIVO")
	private Boolean ativo;  	
			
	@Column(name = "FOTO" )
	private String foto;		
	
	@Column(name = "CELULAR" )
	private String celular;		
	
	@Column(name = "RG" )
	private String rg;		
	
	@Column(name = "DATA_HORA_ASSINATURA")
	private LocalDateTime dataHoraAssinatura;
	
	@Column(name = "DATA_NASCIMENTO")
	private LocalDate dataNascimento;  
				
	@OneToMany()
	private List<Filme> minhaLista;	
		
		
	public  Assinante() {
		
	}
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}
	public Double getDesconto() {
		return desconto;
	}

	public void setDesconto(Double desconto) {
		this.desconto = desconto;
	}
	public LocalDate getDataVencimento() {
		return dataVencimento;
	}

	public void setDataVencimento(LocalDate dataVencimento) {
		this.dataVencimento = dataVencimento;
	}
	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	public Double getValorMensalidade() {
		return valorMensalidade;
	}

	public void setValorMensalidade(Double valorMensalidade) {
		this.valorMensalidade = valorMensalidade;
	}
	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}
	public Boolean getAtivo() {
		return ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}
	public String getFoto() {
		return foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}
	public String getCelular() {
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}
	public String getRg() {
		return rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}
	public LocalDateTime getDataHoraAssinatura() {
		return dataHoraAssinatura;
	}

	public void setDataHoraAssinatura(LocalDateTime dataHoraAssinatura) {
		this.dataHoraAssinatura = dataHoraAssinatura;
	}
	public LocalDate getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(LocalDate dataNascimento) {
		this.dataNascimento = dataNascimento;
	}
	public void setMinhaLista(List<Filme> minhaLista){
		this.minhaLista = minhaLista;
	}
	
	public List<Filme>  getMinhaLista() {
		if(this.minhaLista == null){
			setMinhaLista(new ArrayList<Filme>());
		}
		return this.minhaLista;
	}
		
	public boolean addMinhaLista(Filme filme){
		return getMinhaLista().add(filme);
	}
	
	public boolean removeMinhaLista(Filme filme){
		return getMinhaLista().remove(filme);
	}
	
	
}
//generated by JSetup v0.95 :  at 23 de jun de 2021 23:11:06